version: '3'

networks:
  backend:
    name: backend

services:
  
  mysql-baseapp:
    image: 'mysql:latest'
    container_name: godockerDB
    ports:
      - 3306:3306
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_ROOT_PASSWORD=rootpass
    tty: true
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
  
  webserver-baseapp:
    container_name: godockerAppServer
    ports:
      - 8080:8080
    build:
      dockerfile: Dockerfile
      context: ./webserver-app
    environment:
      - DATABASE_HOST=godockerDB
    depends_on: 
      - mysql-baseapp # This service depends on mysql. Start that first.
    tty: true
    networks:
      - backend

