version: '3'

networks:
  backend:
    name: backend

services:
  
  mysql-baseapp:
    image: 'mysql:latest'
    container_name: godockerDB
## Potentially dangerous, uncomment only if you want to provide direct access to database from other host.
##    ports:
##      - 3306:3306
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_ROOT_PASSWORD=rootpass
    healthcheck:
      test: "/usr/bin/mysql --user=gorm --password=gorm --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    tty: true
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
  
  webserver-baseapp:
    container_name: godockerApp
    ports:
      - 8080:8080
    build:
      dockerfile: Dockerfile
      context: ./webserver-app
    environment:
      - DATABASE_HOST=godockerDB
    depends_on: # This service depends on mysql db container. Start that first.
        mysql-baseapp: 
            condition: service_healthy
    tty: true
    networks:
      - backend

